### ISSUE TITLE
Issue about Page developer/database-schema.adoc

### ISSUE THREAD

**Issue by Verster77** [salesagility/SuiteDocs#650] opened 2024-04-22 08:13 UTC
#### Page with Issue
[](https://suitecrm-docs.netlify.app/schema)

#### What is wrong, less clear, or missing

When going on this page looking for the database schema https://docs.suitecrm.com/developer/database-schema/#_schemaspy_tables_and_diagrams and clicking on please visit the [SuiteCRM Database Schema](https://schema--suitecrm-docs.netlify.com/schema) we get a 404

**Comment by gemartin21** [comment] 2024-05-01 13:15
Thank you for your contribution.  However, this issue appears to be a duplicate of https://github.com/salesagility/SuiteDocs/issues/649 and as such will close this issue.

**Closed** 2024-05-01 13:15 UTC
