### ISSUE TITLE
Duplication of the introduction section

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteDocs#194] opened 2019-01-23 09:45 UTC
@pgorod please pay attention

[Introduction](https://github.com/salesagility/SuiteDocs/tree/master/content/user/Introduction)
and
[introduction](https://github.com/salesagility/SuiteDocs/tree/master/content/user/introduction)

Thus, this section is displayed twice in the manual.

**Comment by pgorod** [comment] 2019-01-23 10:45
Actually there was a lot more duplication of directories... I renamed a bunch of directories to lowercase and `git` seems to have become confused. I am fixing all that now.

Thanks for the warning!

**Comment by pgorod** [comment] 2019-01-23 11:53
Yes, I'll have to do the Spanish part one of these days...

I deleted the `User Interface.ru.adoc` file, thanks.

When I removed the `Introduction` dir, the `diff` was giving me also this detail:

```
diff -r introduction/managing-user-accounts.ru.adoc Introduction/managing-user-accounts.ru.adoc
120,121c120,121
< Группировать закладки link:../user-interface/#_Субпанели[субпанелей] ::  При открытии Формы просмотра субпанели группируются на отдельных закладках.[[Collapced-indicator]]
< Выделять свёрнутые link:../user-interface/#_Субпанели[субпанели], если они содержат записи :: Отображать свёрнутые субпанели различным цветом и индикатором в зависимости от того, содержат они записи или нет.
---
> Группировать закладки link:../user-interface/views/#_Субпанели[субпанелей] ::  При открытии Формы просмотра субпанели группируются на отдельных закладках.[[Collapced-indicator]]
> Выделять свёрнутые link:../user-interface/views/#_Субпанели[субпанели], если они содержат записи :: Отображать свёрнутые субпанели различным цветом и индикатором в зависимости от того, содержат они записи или нет.
```

Can you please check if the one that is there now is the one you want, the latest? Thanks.

**Comment by likhobory** [comment] 2019-01-23 11:59
The second version is correct.

**Comment by likhobory** [comment] 2019-01-23 12:06
And check please /user/modules/LawfulBasis.ru.adoc, the first (older) version is correct
---old version
-Ручное обновление полей производится либо непосредственно в Форме редактирования соответствующей записи, либо в Форме просмотра записи (списка записей), если администратором системы включён функционал link:../../introduction/user-interface/in-line-editing/[быстрой правки]. Для обновления полей сразу в нескольких записях воспользуйтесь функцией link:../../introduction/user-interface/record-management/#_Массовое_обновление_записей[Массового обновления].

---new version
+Ручное обновление полей производится либо непосредственно в Форме редактирования соответствующей записи, либо в Форме просмотра записи (списка записей), если администратором системы включён функционал link:../../introduction/user-interface/#_Быстрая_правка[быстрой правки]. Для обновления полей сразу в нескольких записях воспользуйтесь функцией link:../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей[Массового обновления].

**Comment by pgorod** [comment] 2019-01-23 12:08
Do you mind if I ask you to do a PR with those fixes? I have a hard time finding my way around the Russian language files, I can't even read it or distinguish the characters properly... 😞

**Comment by likhobory** [comment] 2019-01-23 12:10
ок, no problem..

**Comment by pgorod** [comment] 2019-01-23 12:10
Thank yo very much for all your tireless help!

**Comment by likhobory** [comment] 2019-01-23 13:00
All cross references to user-interface are outdated, I'll fix it again, but what is strange: the htmltest does not display any hash errors (hash does not exist)..

**Comment by pgorod** [comment] 2019-01-23 13:32
The directory renames do not create any broken links, because I changed the names following the way that Hugo creates the "slugs" in the final HTML produced (for example, `User Interface` becomes `user-interface`). Since that is what we use when specifying links in `adoc` files, the links keep working).

But maybe you're talking about links broken due to the files moved into subdirs, that does break links...

Are you running `htmltest` with the full rebuild before (delete `public` directory first)?

Can you point me to an example of a broken link we currently have?

**Comment by likhobory** [comment] 2019-01-23 14:42
>talking about links broken due to the files moved into subdirs

Yes


>Are you running htmltest with the full rebuild before

I  cloned your repository into new "clean" directory without public subdirectory


>Can you point me to an example of a broken link we currently have?

all links  to UI section used the following structure before breaking down
`... /#_some-anchor[...]`

and now it should be
`.../some-subdir[...]`

see https://github.com/salesagility/SuiteDocs/pull/159/files

**Comment by pgorod** [comment] 2019-01-24 11:40
Hi @likhobory 

my `htmltest` seems to be catching the problems, this is my output with the current `russian` branch (before merging your new PR with the link fixes):

```
10.0.0.200 | root /var/www/hugo (russian) $ rm -R public/* && hugo --enableGitInfo && ./bin/htmltest  | tee >(grep -v 'errors in\|failed in\|htmltest started\|======' | cut -d '-' -f 1 | sort | uniq -c -w 10)

                   |  EN  |  ES  |  RU
+------------------+------+------+------+
  Pages            |  171 |   40 |  114
  Paginator pages  |    0 |    0 |    0
  Non-page files   |    3 |    3 |    3
  Static files     | 1246 | 1246 | 1246
  Processed images |    0 |    0 |    0
  Aliases          |    1 |    1 |    1
  Sitemaps         |    2 |    1 |    1
  Cleaned          |    0 |    0 |    0

Total in 75404 ms
htmltest started at 10:14:01 on public
========================================================================
hash does not exist --- ru/user/advanced-modules/pdftemplates/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/advanced-modules/pdftemplates/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/pdftemplates/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/pdftemplates/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/pdftemplates/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/events/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/events/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/events/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/events/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/reports/index.html --> ../../introduction/user-interface/#_Управление_дашлетами
hash does not exist --- ru/user/advanced-modules/reports/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/reports/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/reports/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/reports/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/workflow/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/workflow/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/workflow/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/workflow/index.html --> ../../introduction/user-interface/#_Поиск_и_объединение_схожих_записей
hash does not exist --- ru/user/advanced-modules/workflow/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/knowledgebase/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/knowledgebase/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/knowledgebase/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/knowledgebase/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/advanced-modules/knowledgebase/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/advanced-modules/sales/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/introduction/managing-user-accounts/index.html --> ../user-interface/#_Субпанели
hash does not exist --- ru/user/introduction/managing-user-accounts/index.html --> ../user-interface/#_Субпанели
hash does not exist --- ru/user/modules/lawfulbasis/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/modules/lawfulbasis/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/meetings/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/meetings/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/meetings/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/meetings/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/meetings/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/errors/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../introduction/user-interface#_Импорт_данных
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Поиск_и_объединение_схожих_записей
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/accounts/index.html --> ../../../user/introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/emailtemplates/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/surveys/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/surveys/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/surveys/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/surveys/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Интеграция_данных_системы_с_внешними_данными
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Поиск_и_объединение_схожих_записей
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/contacts/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Интеграция_данных_системы_с_внешними_данными
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Поиск_и_объединение_схожих_записей
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/leads/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/documents/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/documents/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/documents/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/documents/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/documents/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/campaigns/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/campaigns/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/campaigns/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/emails/index.html --> ../../introduction/user-interface/#_Навигация_и_сортировка
hash does not exist --- ru/user/core-modules/emails/index.html --> ../../introduction/user-interface/#_Фильтр
hash does not exist --- ru/user/core-modules/emails/index.html --> ../../introduction/user-interface/#_Форма_списка
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/cases/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/spots/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/spots/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/spots/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/spots/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/calls/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/calls/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/calls/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/calls/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/calls/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/notes/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/notes/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/notes/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/notes/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/tasks/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/tasks/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/tasks/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/tasks/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/tasks/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/tasks/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Объединение_дублирующихся_записей
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Поиск_и_объединение_схожих_записей
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/opportunities/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/employees/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/employees/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/employees/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/target-lists/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/target-lists/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/target-lists/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/target-lists/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/target-lists/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/target-lists/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/user/core-modules/projects/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/projects/index.html --> ../../introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/user/core-modules/projects/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/projects/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/projects/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/targets/index.html --> ../../introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/user/core-modules/targets/index.html --> ../../introduction/user-interface/#_Избранное
hash does not exist --- ru/user/core-modules/targets/index.html --> ../../introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/user/core-modules/targets/index.html --> ../../introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/user/core-modules/targets/index.html --> ../../introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/user/core-modules/targets/index.html --> ../../introduction/user-interface/#_Субпанели
hash does not exist --- ru/admin/administration-panel/advanced-openadmin/index.html --> ../../../user/introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/admin/administration-panel/users/index.html --> ../../../user/introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/admin/administration-panel/system/index.html --> ../../../user/introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/admin/administration-panel/system/index.html --> ../../../user/introduction/user-interface/#_Быстрая_правка
hash does not exist --- ru/admin/administration-panel/system/index.html --> ../../../user/introduction/user-interface/#_Субпанели
hash does not exist --- ru/admin/administration-panel/system/index.html --> ../../../user/introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/admin/administration-panel/system/index.html --> ../../../user/introduction/user-interface/#_Импорт_данных
hash does not exist --- ru/admin/administration-panel/system/index.html --> ../../../user/introduction/user-interface/#_Интеграция_данных_системы_с_внешними_данными
hash does not exist --- ru/admin/administration-panel/employee-records/index.html --> ../../../user/introduction/user-interface/#_Экспорт_данных
hash does not exist --- ru/admin/administration-panel/employee-records/index.html --> ../../../user/introduction/user-interface/#_Массовое_обновление_или_удаление_записей
hash does not exist --- ru/admin/administration-panel/search/index.html --> ../../../user/introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/admin/administration-panel/search/index.html --> ../../../user/introduction/user-interface/#_Поиск_информации_в_системе
hash does not exist --- ru/admin/administration-panel/developer-tools/index.html --> ../../../user/introduction/user-interface/#_Управление_дашлетами
hash does not exist --- ru/admin/administration-panel/developer-tools/index.html --> ../../../user/introduction/user-interface/#_Быстрая_правка
========================================================================
✘✘✘ failed in 1.745247546s
191 errors in 272 documents
    191 hash does not exist
```

**Comment by likhobory** [comment] 2019-01-24 12:54
Yes, and in the proposed PR all these links are fixed.

**Comment by pgorod** [comment] 2019-01-24 12:58
Yes, I can confirm there, and it's already in `master` :-)

I was just wondering why your `htmltest` wasn't giving those errors? Sometimes it can be a bit mysterious....

Anyway thanks, I'm closing this.

**Closed by pgorod** 2019-01-24 12:58 UTC

**Comment by likhobory** [comment] 2019-01-24 13:05
ok, but one small comment:
now I have this result with htmltest:

```
./bin/htmltest32  | tee >(grep -v 'errors in\|failed in\|htmltest started\|======' | cut -d '-' -f 1 | sort | uniq -c -w 10)
htmltest started at 03:48:17 on public
========================================================================
hash does not exist --- user/modules/confirmed-opt-in-settings/index.html --> #_sending_resending_opt_in_emails_manually
========================================================================
✘✘✘ failed in 1.400390796s
1 errors in 273 documents
      1 hash does not exist
```
although this internal link is correct..

**Comment by pgorod** [comment] 2019-01-24 13:31
Now I updated my `htmltest` to v.0.10.1 and it also doesn't give any error.

**Comment by likhobory** [comment] 2019-01-24 15:03
Hmm. Tested with 0.9.1, 0.9.2 and 0.10.1 versions. In any case I got this error((

**Comment by pgorod** [comment] 2019-01-25 12:47
Ok, I upgraded my `asciidoctor` and now I get your error. At least the mystery is over 👻 

The problem is the way a `/` character is getting used in the id, versus the link:

`<h2 id="_sendingresending_opt_in_emails_manually">Sending/Resending Opt In Emails Manually</h2>`

but the link uses

` <a href="#_sending_resending_opt_in_emails_manually">manually</a>`

That extra `dash` is the problem. I can just remove the dash in our source, I'll try it and hope that it won't confuse the older Asciidoctors (Netlify is still running 1.5.6.1...)

**Comment by pgorod** [comment] 2019-01-25 13:01
I confirmed that if I fix it for the new Asciidoctor, I break it for the old... :-(

I am not sure if this is an Asciidoctor bug, a Theme bug, a Hugo bug, or even if it is an intended change. But I decided I won't waste any more time with this for now, I will just remove the link with a clever text edit :-)

https://github.com/salesagility/SuiteDocs/commit/1977acef05cc68f27b4c5a41455ad76e5a75e473
