### ISSUE TITLE
Issue about Page developer/Logic Hooks.adoc

### ISSUE THREAD

**Issue by triplertec** [salesagility/SuiteDocs#473] opened 2020-09-24 14:22 UTC
#### What is wrong, less clear, or missing
Custom logic hook files are deleted by the system after a module deployment from "Module Builder", the Ext path is not safe, could you please clarify whether it is the correct path to put

**Comment by pgorod** [comment] 2020-09-24 18:06
@triplertec you probably should be asking in the Forums... this is for documentation updates.

Where exactly did you place the file? Not all `Ext` directories are created equal - some are transitory, some are not.

**Comment by triplertec** [comment] 2020-09-25 06:40
I have a custom module created by 'Module builder' and I added a hook file under Ext directory of the module, then any time when I deploy the module, the hook file is getting deleted. If this is not the correct way to define the hook file, could you please suggest what is the best way to place the hook file for the custom build module? Thanks!

**Comment by pgorod** [comment] 2020-09-25 09:59
Exactly **which** Ext directory, please? There is more than one for each module, and it makes all the difference for this issue.

For example,
`custom\Extension\modules\Accounts\Ext\Vardefs\someField.php` is an input file, does't get overriden

`custom\modules\Accounts\Ext\Vardefs\vardefs.ext.php` is an output file, gets overriden

**Comment by triplertec** [comment] 2020-09-26 01:17
Sorry for the confusion, it is the file under custom\Extension\modules\[Module Builder Module]\Ext\LogicHooks\somefile.php

**Comment by pgorod** [comment] 2020-09-26 09:12
I see. That is the correct one.

I believe that there is a best-practice, probably not documented anywhere, saying that we should use Module Builder only once, initially, and then do the following changes just from Studio - this should avoid your issue.

**Comment by triplertec** [comment] 2020-09-26 14:47
Agree, especially for newbies, it is so disappointed by following the document but the effort is wasted once the deployment is triggered again. Or can it be changed to ignore the custom files under Extension\...\Ext folders the same as the pre-build modules which don't delete them if there is any file not generated by the auto build.

Thanks a lot for your response!

**Comment by pgorod** [comment] 2020-09-26 15:52
No problem. Remember to close this issue if the issue is already clarified. Thanks

**Closed** 2020-09-27 02:50 UTC
